# Generated by scripts/update-tap.sh — do not edit by hand.
class Optictrace < Formula
  desc "Declarative API telemetry and governance gateway"
  homepage "https://dwarka-prasad.github.io/optictrace/"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.7.0/optictrace_0.7.0_darwin_amd64.tar.gz"
      sha256 "ae43b009666bb85d68f945697b39d330e4c63a08fe1cb152feaf50e35ee4e139"
    end
    on_arm do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.7.0/optictrace_0.7.0_darwin_arm64.tar.gz"
      sha256 "c1c7995df3100a749645dc72d3ecbb11d4fe350af49ba2fe8d1e7c9a15b7386b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.7.0/optictrace_0.7.0_linux_amd64.tar.gz"
      sha256 "16abba72e041e4c87dbd7f02d30e3d6e9ab15256fe773e423ba4b7c5c57c16e6"
    end
    on_arm do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.7.0/optictrace_0.7.0_linux_arm64.tar.gz"
      sha256 "4f632913a19de0be4ad6bc1003d95556b6de9295da3ccc39024908ba1ace6718"
    end
  end

  def install
    bin.install "optictrace"
    # The release archive ships an annotated example config and its rule
    # tests; keeping them means `brew install` leaves you with something
    # runnable rather than just a binary.
    pkgshare.install "optic.yaml", "optic.test.yaml"
  end

  def caveats
    <<~EOS
      An example configuration is installed at:
        #{opt_pkgshare}/optic.yaml

      Get started:
        optictrace validate -config #{opt_pkgshare}/optic.yaml
        optictrace run      -config optic.yaml
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/optictrace version")
    # Prove the binary actually works, not just that it runs: validate the
    # shipped config and run its governance assertions.
    system bin/"optictrace", "validate", "-config", pkgshare/"optic.yaml"
    system bin/"optictrace", "test",
           "-config", pkgshare/"optic.yaml",
           "-tests", pkgshare/"optic.test.yaml"
  end
end
