# Generated by scripts/update-tap.sh — do not edit by hand.
class Optictrace < Formula
  desc "Declarative API telemetry and governance gateway"
  homepage "https://dwarka-prasad.github.io/optictrace/"
  license "Apache-2.0"
  # No `version` stanza: Homebrew derives it from the URL, and declaring
  # it as well is flagged by `brew audit` as redundant.

  on_macos do
    on_intel do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.8.0/optictrace_0.8.0_darwin_amd64.tar.gz"
      sha256 "a32148f2b8ec5be439d7ff1e75ac6a658be4843db34b56fb92fd548ce3628fe9"
    end
    on_arm do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.8.0/optictrace_0.8.0_darwin_arm64.tar.gz"
      sha256 "9e7cd11ec9b51f5e615b06d4600c769fb7efc31e93576b425e2f6c6c98fd3829"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.8.0/optictrace_0.8.0_linux_amd64.tar.gz"
      sha256 "0af662da9b1e76ac0f1cdb829999d69fe8d696dc1a38b25dc29479336db700e9"
    end
    on_arm do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.8.0/optictrace_0.8.0_linux_arm64.tar.gz"
      sha256 "110c5dc0e8f0812b91fbc7ea5bdc198deeedcb16ddc8f731086bd493e0ca4cda"
    end
  end

  def install
    bin.install "optictrace"
    # The release archive ships an annotated example config and its rule
    # tests; keeping them means `brew install` leaves you with something
    # runnable rather than just a binary.
    pkgshare.install "optic.yaml", "optic.test.yaml"
  end

  def caveats
    <<~EOS
      An example configuration is installed at:
        #{opt_pkgshare}/optic.yaml

      Get started:
        optictrace validate -config #{opt_pkgshare}/optic.yaml
        optictrace run      -config optic.yaml
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/optictrace version")
    # Prove the binary actually works, not just that it runs: validate the
    # shipped config and run its governance assertions.
    system bin/"optictrace", "validate", "-config", pkgshare/"optic.yaml"
    system bin/"optictrace", "test",
           "-config", pkgshare/"optic.yaml",
           "-tests", pkgshare/"optic.test.yaml"
  end
end
