# Generated by scripts/update-tap.sh — do not edit by hand.
class Optictrace < Formula
  desc "Declarative API telemetry and governance gateway"
  homepage "https://dwarka-prasad.github.io/optictrace/"
  license "Apache-2.0"
  # No `version` stanza: Homebrew derives it from the URL, and declaring
  # it as well is flagged by `brew audit` as redundant.

  on_macos do
    on_intel do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.8.2/optictrace_0.8.2_darwin_amd64.tar.gz"
      sha256 "b7368707b8ea82a8588539df0104447d47a093b97e352ed715fc7482f793b722"
    end
    on_arm do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.8.2/optictrace_0.8.2_darwin_arm64.tar.gz"
      sha256 "f90e9b0e5a08a1f1ee079647f93f2fe59fb346341632caabd548c7305659764c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.8.2/optictrace_0.8.2_linux_amd64.tar.gz"
      sha256 "d9cecb4944f44718e1f5698ebb14ea8c96f0a9f6a4e41e0c2841081eda56e851"
    end
    on_arm do
      url "https://github.com/dwarka-prasad/optictrace/releases/download/v0.8.2/optictrace_0.8.2_linux_arm64.tar.gz"
      sha256 "490aa173c6bd9e48a15049842327ae1aa3e91c7cc00e9a39510bff0066fb83e2"
    end
  end

  def install
    bin.install "optictrace"
    # The release archive ships an annotated example config and its rule
    # tests; keeping them means `brew install` leaves you with something
    # runnable rather than just a binary.
    pkgshare.install "optic.yaml", "optic.test.yaml"
  end

  def caveats
    <<~EOS
      An example configuration is installed at:
        #{opt_pkgshare}/optic.yaml

      Get started:
        optictrace validate -config #{opt_pkgshare}/optic.yaml
        optictrace run      -config optic.yaml
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/optictrace version")
    # Prove the binary actually works, not just that it runs: validate the
    # shipped config and run its governance assertions.
    system bin/"optictrace", "validate", "-config", pkgshare/"optic.yaml"
    system bin/"optictrace", "test",
           "-config", pkgshare/"optic.yaml",
           "-tests", pkgshare/"optic.test.yaml"
  end
end
